### PR TITLE
Feat/portal charts

### PR DESCRIPTION
**Pull request by anngvu**
Related to [NFINT-491](https://sagebionetworks.jira.com/browse/NFINT-491?atlOrigin=eyJpIjoiODViNzUxMGFlYzAzNDg4NzliODQ3ZGM1OTMwZjM0OWIiLCJwIjoiaiJ9)

### CODE REVIEW

**Comment by anngvu** [comment]
Need to fix Docker build:

> 5.641 The following packages have unmet dependencies:
> 5.738  libc6-dev : Breaks: binutils (< 2.38) but 2.37-7 is to be installed

**Comment by anngvu** [comment]
Will update Dockerfile in separate PR

**Comment by allaway** [comment]
I installed mermaid and rendered the output from `flowchart <- processing_flowchart(year = 1)`, attached. Is it possible that some raw data nodes are missing? Thinking specifically about the JHU biobank with three edges going into one raw data node. 
output

**Review by allaway — APPROVED** [review]
Assuming my the output i pasted in my other comment is expected, LGTM!

**Comment by jaybee84** [comment]
Aha! this is the PR I was looking for.

It looks like I updated the data table right before @allaway  review/updated rendering of the output. The updated output is expected.

SynXX302 is the input raw data node for both synXX189 and synXX656 output folders (somatic and germline variants). However, SynXX641 should be deleted since it was a test of the workflows before final processing was done. @anngvu I am happy to delete the corresponding row in the internal tracking table, but want to confirm with you before I go ahead :)

**Comment by anngvu** [comment]
Hey @jaybee84 Yep, please delete row if it is a test and shouldn't be in final display.

**Comment by jaybee84** [comment]
done, portal charts is ready to be rebuilt

**Comment by jaybee84** [comment]
@anngvu the rendering of this image AFAIR had the nodes to be clickable. In the version that is surfaced in the portal (https://www.synapse.org/#!Synapse:syn26451327/wiki/620082) the image is static. Is that the behavior you are expecting?

**Pull request merged**
