### PR TITLE
Improve implementation of meta_qc_* utils

### LINKED ISSUE #204: Automated dataset qc improvements
- [x] Better summarized warning/error messages, e.g. for
  - [x] https://github.com/nf-osi/dcc-site/issues/99#issuecomment-2469442863, should say that no dataset folders are found but there are data files
  - [x] https://github.com/nf-osi/dcc-site/issues/1014#issuecomment-2451043379, don't show unnecessary warning
- [x] Try harder at detecting nested datasets, going to one deeper level. This would be more consistent with our current [docs](https://help.nf.synapse.org/NFdocs/how-to-organize-data), where we acknowledge that one additional level of nesting is reasonable (to organize by milestone/cohort/other types of batches within the same data type). This will help avoid false negative results for datasets with one more level of organization such as in 
  - [x] https://github.com/nf-osi/dcc-site/issues/139
  - [x] https://github.com/nf-osi/dcc-site/issues/111

### PR DESCRIPTION
**Pull request by anngvu**
Close #204. **Reviewers can see example tests and output improvements for some original motivating cases here:**
- https://github.com/nf-osi/dcc-site/issues/139#issuecomment-2501677571 
- https://github.com/nf-osi/dcc-site/issues/111#issuecomment-2502143842

Typically these functions should be automated in the background when the time comes instead of being manually run. However, to run this manually:

```
project_id <- "syn1234"
meta_qc_project(project_id)
```

**Output table is rendered in a markdown report, which can be inserted anywhere that accepts markdown -- such as GitHub issue threads as seen above.

**This is essentially done but needs to hang out in the merge queue/blocked until #202 is merged first since it will rely on/need to incorporate the changes in `annotation_qc.R` made in #202.**

### CODE REVIEW

**Comment by anngvu** [comment]
Ready for review **(main reviewer @allaway)**. Others for awareness.

**Comment by cconrad8** [comment]
@anngvu I tried [this project](https://www.synapse.org/Synapse:syn21650484/files/) and it says 0 files found for Raw Data (Young) and the subfolders.  I'm wondering if there might be some issues with the subfolders since Raw Data (Young) has many subfolders under neath it. 

```
> meta_qc_project("syn21650484")
Datasets found for QC:
Bulk RNA Sequencing Donor RGCs
Raw Data (Young)
(found 3 files for Bulk RNA Sequencing Donor RGCs)
Found synapse_storage_manifest for dataset named 'Bulk RNA Sequencing Donor RGCs' (syn21650485)!
Downloading files: 100%|██████████| 1.57k/1.57k [00:00<00:00, 4.23kB/s, syn63811146]Downloaded syn63811146 to c:\users\cconrad\.synapsecache\747\148846747\synapse_storage_manifest_rnaseqtemplate.csv
Downloading files: 100%|██████████| 1.57k/1.57k [00:00<00:00, 4.19kB/s, syn63811146]Temp manifest files removed for dataset syn21650485
(found 0 files for Raw Data (Young))
Trying instead: Aim 2, Improving cell engraftment with scaffold; Aim 3, Pig RGCs development
(found 0 files for Aim 2, Improving cell engraftment with scaffold)
(found 0 files for Aim 3, Pig RGCs development)
```

**Comment by anngvu** [comment]
@cconrad8 Yeah, this is a good example of where the project structure is structured in a way that we do not expect. Usually there is not a Raw Data folder under a Data folder. If we move **Aim 2** and **Aim 3** folders to directly under Data, it should work; the check was only updated to accommodate an additional grouping level by Aim or Batch folders etc. 
image

**Comment by cconrad8** [comment]
Ok @anngvu that makes sense!

**Review by cconrad8 — APPROVED** [review]

**Pull request merged**
