### PR TITLE
update annotate_with_manifest

### PR DESCRIPTION
**Pull request by allaway**
This is a minor change to fix the annotate_with_manifest function to be compatible with newer versions of synapser

### CODE REVIEW

**Comment by anngvu** [comment]
@allaway `develop` currently doesn't import synapser yet -- import and usage of `synapser` is still only in https://github.com/nf-osi/nfportalutils/tree/develop-synapser. And that branch is also on hold because of https://python-docs.synapse.org/#notice-for-the-upcoming-v50-release, which I think will contain a bunch of breaking changes so it would be a lot of misplaced effort to do the refactor to only have to figure out how to rewrite everything again.

**Comment by allaway** [comment]
Whoops, good point. 

I still wonder if it would be worth changing this function to: 

```

    old_annots <- .syn$getAnnotations(entity)
    ent <- .syn$get(entity, downloadFile = FALSE)
    ent$annotations <- c(old_annots, annotations[[entity]])
    .syn$store(ent)

```

Based on my reading of the pubpub, I don't _believe_ this will break in v5.0.0, but maybe it will? @BryanFauble @thomasyu888 would you be willing to comment?

**Comment by anngvu** [comment]
So I think we can make the change to work with Python client v4.4.0 but still implement using reticulate.

**Comment by allaway** [comment]
Haha, I think our similar suggestions crossed paths :)

**Comment by anngvu** [comment]
Yeah, let's reopen since I think it's worth it to make changes given second thoughts / suggestions above.

**Review by anngvu — CHANGES_REQUESTED** [review]
Let's go with more compatible approach in https://github.com/nf-osi/nfportalutils/pull/197#issuecomment-2447577440

**Comment by BryanFauble** [comment]
> Whoops, good point.
> 
> I still wonder if it would be worth changing this function to:
> 
> ```
> 
>     old_annots <- .syn$getAnnotations(entity)
>     ent <- .syn$get(entity, downloadFile = FALSE)
>     ent$annotations <- c(old_annots, annotations[[entity]])
>     .syn$store(ent)
> ```
> 
> Based on my reading of the pubpub, I don't _believe_ this will break in v5.0.0, but maybe it will? @BryanFauble @thomasyu888 would you be willing to comment?

@allaway @anngvu 
I honestly don't have a clear picture how the R side of the changes will be impacted by the planned v5.0.0 changes for the python client. I was pushing forward heavily on getting everything in place for v5.0.0 before other priorities came up and I'm uncertain on the timeline when this will be in place. I will be making it very clear in all documentation before we push out any new major versions exactly what things are expected to/not work.

Since we have a light shim layer between the R client and the python client that is likely where we can maintain some level of backwards compatibility.


With that being said, I would not count on the v5.0.0 release being ready in the short-term, so if you two need to move forward on a solution for what you're working on here, please do so.

**Comment by anngvu** [comment]
@allaway I found an alternative implementation that might be a little better. Also we need to add more tests for this, so going to address as part of the overall upgrade epic.

**Comment by thomasyu888** [comment]
> I found an alternative implementation that might be a little better. Also we need to add more tests for this, so going to address as part of the overall upgrade epic.

@anngvu Could you share the alternative implementation?  That may help us in the long term as we continue to patch things up

**Pull request closed without merging**
