### PR TITLE
Feature new project mod

### LINKED ISSUE #4: project creation function
take project creation script and function-ize it

### PR DESCRIPTION
**Pull request by anngvu**
Creates a new project. Main difference from script in https://github.com/nf-osi/DCC are:

- Includes data curator wiki subpage.
- Includes utility function to pull data from GSheets instead of entering parameters manually.
- Factoring out some of the functionality to later add nested folders.

### CODE REVIEW

**Comment by anngvu** [comment]
Looks like build failed only on MacOs (something to do with conda).

**Comment by allaway** [comment]
Sorry for my delay. Not sure what the deal is but when I try to install on my mac I get: 

```
==> R CMD INSTALL --no-multiarch --with-keep.source nfportalutils

* installing to library ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
* installing *source* package ‘nfportalutils’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
sh: line 1: 80962 Abort trap: 6           '/anaconda3/bin/conda' info --json 2> /dev/null
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010df625c0 (most recent call first):
** testing if installed package can be loaded from final location
sh: line 1: 80980 Abort trap: 6           '/anaconda3/bin/conda' info --json 2> /dev/null
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000011389c5c0 (most recent call first):
** testing if installed package keeps a record of temporary installation path
* DONE (nfportalutils)
```

However, it still appears to install alright.

**Comment by allaway** [comment]
Well, I reinstalled and couldn't reproduce the thing I mentioned above.

**Comment by allaway** [comment]
I made a small change to export the new_project function (see https://github.com/anngvu/nfportalutils/pull/2). I tried running the new_project function but hit a permissions error, though it's not clear to me why that's happening: 

```

> syn_login()
Welcome, Robert Allaway!


UPGRADE AVAILABLE

A more recent version of the Synapse Client (2.5.1) is available. Your version (2.2.2) can be upgraded by typing:
    pip install --upgrade synapseclient

Python Synapse Client version 2.5.1 release notes

https://python-docs.synapse.org/build/html/news.html

> nfportalutils::new_project('foo', 'foo', 'foo', NULL, 'foo', 'foo', 'CTF', "foo", TRUE)
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  SynapseHTTPError: 403 Client Error: 
Lack of READ permission on the requested entity. 
9.
stop(structure(list(message = "SynapseHTTPError: 403 Client Error: \nLack of READ permission on the requested entity.", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("1   reticulate.so                       0x0000000115a82f1d _ZN4Rcpp9exceptionC2EPKcb + 221", 
    "2   reticulate.so                       0x0000000115a8bdb5 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 53",  ... 
8.
_raise_for_status at exceptions.py#160
7.
_handle_synapse_http_error at client.py#3742
6.
_rest_call at client.py#3763
5.
restPOST at client.py#3796
4.
findEntityId at client.py#3693
3.
store at client.py#1058
2.
.syn$store(project) at new_project.R#37
1.
nfportalutils::new_project("foo", "foo", "foo", NULL, "foo", 
    "foo", "CTF", "foo", TRUE) 
```

**Comment by anngvu** [comment]
I'll take a look...

**Comment by anngvu** [comment]
The `Lack of READ permission on the requested entity.` probably means there was a name collision with a private project. If there's a name collision with an existing project, the project won't be created and returns another access error; added working and failed examples in `example_script/new_project.R`.

**Comment by anngvu** [comment]
:raised_eyebrow: CI passes on macOS now; honestly still not sure what the original error meant, but I guess it resolved on its own?

**Review by allaway — APPROVED** [review]
Works great for me now. Nice sleuthing on the bug being the result of an existing project with that name. Totally makes sense in retrospect, but that didn't even occur to me!

Not sure why the mac build failed, though I have seen builds fail in the past when some dependency was temporarily not available...maybe that's what happened?

**Pull request merged**
