### PR TITLE
change people functions to synapser

### LINKED ISSUE #94: Refactor synapse-adjacent functions to use new reticulate-based synapser
We should drop the custom import of the synapse python client in lieu of the new reticulate-based synapser, which likely will have better ongoing support (at least compared to us maintaining a custom import of the client) and will make it easier for users of this package to import in additional synapser functions/R docs instead of having to use synapseclient via reticulate.

### PR DESCRIPTION
**Pull request by allaway**
This PR introduces synapser to `Imports` and refactors the add_people_from_table and  .store_rows functions to use synapser. Modified the .check_login function to look for `syn` object imported by library(synapser).

### CODE REVIEW

**Comment by allaway** [comment]
@anngvu , any ideas on why it would fail to build this package with synapser on mac and windows but work fine on ubuntu?

**Comment by anngvu** [comment]
@allaway Since I'm mainly Linux, I'm honestly sure what the Mac and Windows issues are -- the logs aren't super helpful -- will need to look more into it.

**Comment by anngvu** [comment]
@allaway OK, I think this is actually a GH workflow issue.

**Comment by anngvu** [comment]
So testing locally:
- On Sage Mac laptop, building `synapser` when installing with `pak` was not an issue.
- On borrowed Windows laptop, couldn't build `synapser` when installing with `pak` and there was just not enough information to resolve.

So I revised the workflow to use precompiled `synapser` from Synapse repo when building from source fail for those OS platforms -- this corresponds with the official installation instructions and is how most users would obtain `synapser` in any case.

**Review by anngvu — APPROVED** [review]
I think a hint of what source table/column usually maps to in the NF context would be nice, but as functionality goes everything works with `people_table_id = "syn23564971", people_column = "ownerID", source_table_id = "syn16858331", source_column = "createdBy", both dry_run TRUE and FALSE`, so merging.

**Pull request merged**
