### PR TITLE
Update set annotations usage

### LINKED ISSUE #199: Remove deprecated `getAnnotations`/`setAnnotations` usage to help update to Python client >= v4.3.1
Usage of these [deprecated functions](https://python-docs.synapse.org/news/#210-2020-06-16) means we've been holding back on moving to new version of the client (though this is possibly not the only issue to resolve). To feel safer moving to the target new version, this is one of the more obvious updates to make.

### PR DESCRIPTION
**Pull request by anngvu**
Close #199 and adds vignette. Let's merge this first, and then #186 will rebase to take advantage of it. This makes the necessary changes in:

- [R/annotation_qc.R](https://github.com/nf-osi/nfportalutils/compare/develop...update-set-annotations-usage#diff-3c79e46399d2e1dcd2b1b674e5df3afa8fe1d786e9aa16c92b294224b2f161db)
- [R/annotations.R](https://github.com/nf-osi/nfportalutils/compare/develop...update-set-annotations-usage#diff-fdda277fa760763ab947c61c4b64cb05d41ce13b2bd61994c6eb25855bb2f8fb)
- [R/calculate_related_studies.R](https://github.com/nf-osi/nfportalutils/compare/develop...update-set-annotations-usage#diff-721be23b2831e70edef95712bf7359402238277a4759b751bace8b6c84ab13cd)
- [R/register_study.R](https://github.com/nf-osi/nfportalutils/compare/develop...update-set-annotations-usage#diff-3eb6811b82f0425666cce0d62f912c0bb8374b4df28874012ffc992c047f0411)

While #186 makes changes in:
- R/basic_utils.R
- R/datasets.R
- R/find.R
- R/nextflow_annotation_utils.R
- R/provenance.R

### CODE REVIEW

**Comment by allaway** [comment]
I'm happy to test this :)

**Comment by aditya-nath-sage** [comment]
Happy to test it

**Comment by aditya-nath-sage** [comment]
here is the manifest generated: https://docs.google.com/spreadsheets/d/1P4AyJyzafDRCq3sUclUdKt83mTAJIvzZPNvLKswGqU8/edit?gid=0#gid=0

Seems like most fields are still missing?

**Comment by anngvu** [comment]
@aditya-nath-sage Use the other id: syn53975003

image

**Comment by anngvu** [comment]
@aditya-nath-sage Reminder to 1) run through `vignettes/annotate-data-intro.Rmd` and 2) test `annotate_with_manifest(manifest)` as part of the Jira ticket [NFINT-950](https://www.google.com/url?q=https://sagebionetworks.jira.com/browse/NFINT-950)

**Comment by aditya-nath-sage** [comment]
manifest_generate test with syn53975003 :https://docs.google.com/spreadsheets/d/1A17I4pJ9zmwf-0t1zDjVu_Ns9x20GS7ZoPL-R0EIjhk/edit?gid=0#gid=0

Seems to populate well!

**Comment by aditya-nath-sage** [comment]
Set annotations for dev project (syn26462036) and then created manifest:
Looks to have added annotations to a row!
https://docs.google.com/spreadsheets/d/1OrWpemuxs0unu2OOd23kbN5tEZyvxTXt3m1lv_8RlU8/edit?gid=0#gid=0

**Comment by anngvu** [comment]
@aditya-nath-sage Great! Thanks, this seems good enough validation that R and these package functions are clear and can be applied by you for test scenarios as well as real scenarios.

Let me know if you have any questions on "how do I use this?" or "this seems to not be working for me", otherwise you can submit review approval.

**Review by aditya-nath-sage — APPROVED** [review]

**Pull request merged**
